### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by eikebartels** [iakta/flutter_flavors#1]
Did you get to managed to run the dev flavour in Android Studio?

**Comment by zontarian** [comment]
Hello. Yes, it works usually. 
What issues are you experiencing?

**Comment by eikebartels** [comment]
Ok yea it works. 
The configurations were not populated in Android studio and then I forgot to add the flavour. 
Works! Thanks for the tutorial 
![screen shot 2018-05-08 at 14 03 01](https://user-images.githubusercontent.com/767979/39756119-9faa3e86-52c8-11e8-83c3-61621035a142.png)
![screen shot 2018-05-08 at 14 02 57](https://user-images.githubusercontent.com/767979/39756120-9fc2a4d0-52c8-11e8-9bbc-420f96a59bf8.png)
