### ISSUE TITLE
How to change Bundle identifier on iOS ?

### ISSUE THREAD

**Issue by sestegra** [iakta/flutter_flavors#6]
With your last commit, I don't see how to change Bundle Identifier anymore.

**Comment by imtoori** [comment]
Hello, sorry but I missed to specify something.
Now the bundle_suffix is a variable defined in the xcconfig file.
Let me know if it's ok

**Comment by sestegra** [comment]
I still have an issue with #5.
Which versions of Flutter and XCode are you using ?

**Comment by sestegra** [comment]
@Salvatore-Giordano 
I went a step further to manage assets per flavor and platform in following project.
https://github.com/sestegra/flutter_assets_flavors

I thank you for your support.
